export class QuestionBaseDto {
  index: number; // autogenerated by question index
  type: string;
  weight: number;
  statement: string;
  hints?: { id: string; content: string }[];
}

export class QuestionMatchDto extends QuestionBaseDto {
  type = 'match' as const;
  pairs: {
    id: string;
    left: string;
    right: string;
    match_id: string;
  }[];
}

export class QuestionFillDto extends QuestionBaseDto {
  type = 'fill' as const;
  blanks: {
    id: string;
    correct_answers: string[];
    position: number;
  }[];
  complete_solution: string;
}

export class QuestionOrderDto extends QuestionBaseDto {
  type = 'order' as const;
  items: {
    id: string;
    content: string;
  }[];
  correct_order: string[];
}

export class QuestionSelectDto extends QuestionBaseDto {
  type = 'select' as const;
  options: { id: string; content: string }[];
  correct_options: string[];
  solution_steps: { step: number; description: string }[];
}

export class QuestionSolveDto extends QuestionBaseDto {
  type = 'solve' as const;
  expected_answer: string;
  solution_steps: { step: number; description: string }[];
}

export class QuestionTrueFalseDto extends QuestionBaseDto {
  type = 'truefalse' as const;
  correct_answer: boolean;
  explanation: string;
}
